# Generated by Django 3.2.2 on 2021-05-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_catcart_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catcart',
            name='brands',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptops'), ('TW', 'Men'), ('BW', 'Women'), ('ND', 'Networking Devices'), ('TV', 'TVs')], max_length=3),
        ),
    ]
