# Generated by Django 3.2.2 on 2021-05-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210515_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptops'), ('MF', 'Men'), ('FF', 'Women'), ('ND', 'Networking Devices'), ('TV', 'TVs')], max_length=3),
        ),
    ]
